version: "3.3"
services:
  database:
    build: ./database
  youtube:
    build: ./youtube
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./youtube:/app
    depends_on:
      - database
